from pydantic import BaseModel, Field, field_validator


class UsageStats(BaseModel):
    """Statistics from a single Claude Code invocation."""

    input_tokens: int = Field(default=0)  # Prompt tokens sent to the model
    output_tokens: int = Field(default=0)  # Completion tokens generated by the model
    cache_creation_input_tokens: int = Field(default=0)  # Tokens written to prompt cache
    cache_read_input_tokens: int = Field(default=0)  # Tokens served from prompt cache

    @field_validator("input_tokens", "output_tokens", "cache_creation_input_tokens", "cache_read_input_tokens", mode="before")
    @classmethod
    def _coerce_none_to_zero(cls, v: int | None) -> int:
        return v or 0

    def add(self, other: "UsageStats") -> None:
        """Accumulate another stats into this one in-place."""
        if other is None:
            return
        self.input_tokens += other.input_tokens
        self.output_tokens += other.output_tokens
        self.cache_creation_input_tokens += other.cache_creation_input_tokens
        self.cache_read_input_tokens += other.cache_read_input_tokens

    @classmethod
    def sum(cls, *usages: "UsageStats | None") -> "UsageStats | None":
        """Return the sum of all non-None usages, or None if all are None."""
        result = cls()
        for u in usages:
            if u is not None:
                result.add(u)
        return result if (result.input_tokens or result.output_tokens) else None
